ci: Check secret access and set job dependencies

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,8 +6,8 @@ concurrency:
 
 on:
   push:
-  pull_request:
-    types: [labeled]
+  pull_request_target:
+    types: [labeled, opened, synchronize]
   workflow_dispatch:
     inputs:
       JDK_VERSION:
@@ -24,9 +24,34 @@ permissions:
   pull-requests: write
 
 jobs:
+  check-secrets:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'safe to test')
+    steps:
+      - name: Check secrets
+        run: |
+          if [ -z "${{ secrets.KEY_STORE }}" ]; then
+            echo "::error::No secret defined or no access to secrets"
+            exit 1
+          fi
+          echo "::notice::Secrets seems available"
+
+      - name: Get User Permission
+        id: checkAccess
+        uses: actions-cool/check-user-permission@v2
+        with:
+          require: write
+          username: ${{ github.triggering_actor }}
+
+      - name: Check User Permission
+        if: steps.checkAccess.outputs.require-result == 'false'
+        run: |
+          echo "::error::${{ github.triggering_actor }} does not have permissions on this repo.\nCurrent permission level is ${{ steps.checkAccess.outputs.user-permission }}\nJob originally triggered by ${{ github.actor }}"
+          exit 1
 
   checkstyle:
     runs-on: ubuntu-latest
+    needs: check-secrets
     if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'safe to test')
     steps:
 
@@ -90,6 +115,7 @@ jobs:
 
   lint:
     runs-on: ubuntu-latest
+    needs: check-secrets
     if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'safe to test')
     steps:
       - name: Checkout the latest code
@@ -157,6 +183,7 @@ jobs:
     # > are 2-3 times faster than the macOS ones which are also a lot more expensive.
     # https://github.com/ReactiveCircus/android-emulator-runner#running-hardware-accelerated-emulators-on-linux-runners
     runs-on: ubuntu-latest
+    needs: check-secrets
     if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'safe to test')
     strategy:
       fail-fast: false
