WIP just for testing do not merge

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -36,18 +36,18 @@ jobs:
           fi
           echo "::notice::Secrets seems available"
 
-      - name: Get User Permission
-        id: checkAccess
-        uses: actions-cool/check-user-permission@v2
-        with:
-          require: write
-          username: ${{ github.triggering_actor }}
+      # - name: Get User Permission
+      #   id: checkAccess
+      #   uses: actions-cool/check-user-permission@v2
+      #   with:
+      #     require: write
+      #     username: ${{ github.triggering_actor }}
 
-      - name: Check User Permission
-        if: steps.checkAccess.outputs.require-result == 'false'
-        run: |
-          echo "::error::${{ github.triggering_actor }} does not have permissions on this repo.\nCurrent permission level is ${{ steps.checkAccess.outputs.user-permission }}\nJob originally triggered by ${{ github.actor }}"
-          exit 1
+      # - name: Check User Permission
+      #   if: steps.checkAccess.outputs.require-result == 'false'
+      #   run: |
+      #     echo "::error::${{ github.triggering_actor }} does not have permissions on this repo.\nCurrent permission level is ${{ steps.checkAccess.outputs.user-permission }}\nJob originally triggered by ${{ github.actor }}"
+      #     exit 1
 
   checkstyle:
     runs-on: ubuntu-latest
